apiVersion: v1
kind: Pod
metadata:
  name: busyboxtst
  namespace: jobs
spec:
  containers:
  - name: busyboxtst
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

