kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: jobs
  name: deployment-manager
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["deployments", "replicasets", "pods", "jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # You can also use ["*"]
